import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/header";
import Footer from "./components/footer";
import clsx from "clsx";
import dynamic from "next/dynamic";
import I18n from "./components/i18n";
import { Toaster } from 'react-hot-toast';

const inter = Inter({ subsets: ["latin"] });

const ReduxProvider = dynamic(() => import("./StoreProvider"), {
  ssr: false,
});

export const metadata = {
  title: "Myagkof Furniture App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <head>
        <meta
          name="google-site-verification"
          content="LFzL05vfJF8gEKJvfuHLL3CkUbxPJj-Px10ALJbDtJE"
        />
      </head>
      <body
        className={clsx(inter.className, "flex flex-col min-h-[100vh] w-full")}
      >
        <ReduxProvider>
          <I18n>
            <Header />
            <div>{children}</div>
            <Toaster position="top-center" reverseOrder={false} />
            <Footer />
          </I18n>
        </ReduxProvider>
      </body>
    </html>
  );
}
